name: PlatformIO CI
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio==6.1.6

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install web dependencies
        working-directory: ./web
        run: npm install

      - name: Build web app
        working-directory: ./web
        run: npm run build

      - name: Build project
        run: pio run -e esp32

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ".pio/build/esp32/firmware.bin,.pio/build/esp32/firmware-full.bin"
